name: Publish plugin release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Plugin release version'
        required: true
      plugin_upload_token:
        description: 'Token for uploading plugin to jetbrains repository'
        required: true

env:
  NEW_VERSION: ${{ github.event.inputs.version }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure main branch
        run: ./.github/sh/validate_main_branch.sh

      - name: Validate plugin version update
        run: ./.github/sh/validate_version_update.sh "pluginVersion" "$NEW_VERSION"

  release:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update plugin version
        run: ./.github/sh/update_release_version.sh "pluginVersion" "$NEW_VERSION"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update plugin version to ${{ env.NEW_VERSION }}"
          file_pattern: gradle.properties
          skip_dirty_check: true

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          toTag: HEAD
          failOnError: true
          configuration: .github/changelogconfig/plugin-configuration.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish intellij plugin release
        run: PLUGIN_UPLOAD_TOKEN=${{ github.event.inputs.version }} ./gradlew :elmslie-plugin:publishPlugin
      # run: PLUGIN_UPLOAD_TOKEN=${{ secrets.PLUGIN_UPLOAD_TOKEN }} ./gradlew :elmslie-plugin:publishPlugin

      - name: Create github release
        uses: ncipollo/release-action@v1
        with:
          name: "Plugin ${{ env.NEW_VERSION }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "plugin-${{ env.NEW_VERSION }}"
          body: ${{ steps.github_release.outputs.changelog }}
          artifacts: "elmslie-plugin/build/distributions/*.zip"
